/**
 * @file app/(marketing)/pricing/page.tsx
 * @description Pricing page for CopyWorx
 * 
 * Sections:
 * - Pricing tiers
 * - Feature comparison
 * - FAQ section
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import { Check, X, HelpCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Pricing',
  description: 'Simple, transparent pricing for teams of all sizes. Start free and scale as you grow.',
};

/**
 * Pricing tiers configuration
 */
const pricingTiers = [
  {
    name: 'Free',
    description: 'Perfect for trying out CopyWorx',
    price: '$0',
    period: 'forever',
    cta: 'Get Started',
    ctaVariant: 'outline' as const,
    highlighted: false,
    features: [
      { name: '1,000 words per month', included: true },
      { name: '5 templates', included: true },
      { name: 'Basic analytics', included: true },
      { name: 'Community support', included: true },
      { name: 'Team collaboration', included: false },
      { name: 'Custom brand voice', included: false },
      { name: 'API access', included: false },
      { name: 'Priority support', included: false },
    ],
  },
  {
    name: 'Pro',
    description: 'For professional copywriters',
    price: '$29',
    period: 'per month',
    cta: 'Start Free Trial',
    ctaVariant: 'amber' as const,
    highlighted: true,
    features: [
      { name: 'Unlimited words', included: true },
      { name: '50+ templates', included: true },
      { name: 'Advanced analytics', included: true },
      { name: 'Email support', included: true },
      { name: 'Team collaboration (3 seats)', included: true },
      { name: 'Custom brand voice', included: true },
      { name: 'API access', included: false },
      { name: 'Priority support', included: false },
    ],
  },
  {
    name: 'Team',
    description: 'For growing teams',
    price: '$79',
    period: 'per month',
    cta: 'Start Free Trial',
    ctaVariant: 'ink' as const,
    highlighted: false,
    features: [
      { name: 'Unlimited words', included: true },
      { name: '50+ templates', included: true },
      { name: 'Advanced analytics', included: true },
      { name: 'Priority email support', included: true },
      { name: 'Team collaboration (10 seats)', included: true },
      { name: 'Custom brand voice', included: true },
      { name: 'API access', included: true },
      { name: 'Dedicated account manager', included: true },
    ],
  },
] as const;

/**
 * FAQ items
 */
const faqItems = [
  {
    question: 'What counts as a word?',
    answer: 'Every word generated by our AI counts toward your monthly limit. Edited or manually typed content does not count.',
  },
  {
    question: 'Can I change plans anytime?',
    answer: 'Yes! You can upgrade or downgrade your plan at any time. Changes take effect at the start of your next billing cycle.',
  },
  {
    question: 'Is there a free trial?',
    answer: 'Yes, all paid plans come with a 14-day free trial. No credit card required to start.',
  },
  {
    question: 'What happens if I exceed my word limit?',
    answer: 'On the Free plan, you\'ll need to wait until next month or upgrade. On paid plans, you can purchase additional words as needed.',
  },
  {
    question: 'Do you offer discounts for annual billing?',
    answer: 'Yes! Save 20% when you choose annual billing on any paid plan.',
  },
  {
    question: 'Can I get a refund?',
    answer: 'We offer a 30-day money-back guarantee on all paid plans. If you\'re not satisfied, contact us for a full refund.',
  },
] as const;

/**
 * Pricing page component
 */
export default function PricingPage() {
  return (
    <>
      {/* Hero Section */}
      <section className="relative overflow-hidden py-24 md:py-32">
        {/* Background */}
        <div className="absolute inset-0 bg-gradient-to-b from-amber-50/50 via-transparent to-transparent" />
        
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative">
          <div className="max-w-3xl mx-auto text-center">
            <Badge variant="amber" className="mb-6">Pricing</Badge>
            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold text-ink-900 mb-6">
              Simple, transparent pricing
            </h1>
            <p className="text-lg md:text-xl text-ink-600 leading-relaxed">
              Start free and scale as you grow. No hidden fees, no surprises.
            </p>
          </div>
        </div>
      </section>

      {/* Pricing Cards */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {pricingTiers.map((tier) => (
              <Card 
                key={tier.name}
                className={cn(
                  'relative flex flex-col',
                  tier.highlighted 
                    ? 'border-amber-400 shadow-xl scale-105 z-10' 
                    : 'border-border/50'
                )}
              >
                {tier.highlighted && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                    <Badge variant="amber" className="shadow-lg">
                      Most Popular
                    </Badge>
                  </div>
                )}
                
                <CardHeader className="pb-4">
                  <CardTitle className="font-display text-2xl">{tier.name}</CardTitle>
                  <CardDescription>{tier.description}</CardDescription>
                </CardHeader>
                
                <CardContent className="flex-1">
                  {/* Price */}
                  <div className="mb-6">
                    <span className="font-display text-5xl font-bold text-ink-900">
                      {tier.price}
                    </span>
                    <span className="text-ink-500 ml-2">
                      {tier.period}
                    </span>
                  </div>
                  
                  {/* Features */}
                  <ul className="space-y-3">
                    {tier.features.map((feature) => (
                      <li 
                        key={feature.name}
                        className="flex items-start gap-3"
                      >
                        {feature.included ? (
                          <Check className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                        ) : (
                          <X className="h-5 w-5 text-ink-300 shrink-0 mt-0.5" />
                        )}
                        <span className={cn(
                          'text-sm',
                          feature.included ? 'text-ink-700' : 'text-ink-400'
                        )}>
                          {feature.name}
                        </span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
                
                <CardFooter className="pt-4">
                  <Button 
                    variant={tier.ctaVariant} 
                    className="w-full" 
                    size="lg"
                    asChild
                  >
                    <Link href="/sign-up">{tier.cta}</Link>
                  </Button>
                </CardFooter>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Enterprise Section */}
      <section className="py-16 bg-ink-950 text-white">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center">
            <Badge variant="outline" className="mb-4 border-amber-500/30 text-amber-400">
              Enterprise
            </Badge>
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              Need more? Let's talk.
            </h2>
            <p className="text-ink-300 mb-8 max-w-2xl mx-auto">
              For larger teams with custom requirements, we offer tailored solutions 
              with dedicated support, custom integrations, and volume discounts.
            </p>
            <Button variant="amber" size="lg" asChild>
              <Link href="mailto:sales@copyworx.app">Contact Sales</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-24 md:py-32 bg-gradient-to-b from-white to-ink-50/50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            {/* Section Header */}
            <div className="text-center mb-12">
              <Badge variant="secondary" className="mb-4">FAQ</Badge>
              <h2 className="font-display text-3xl md:text-4xl font-bold text-ink-900 mb-4">
                Frequently asked questions
              </h2>
              <p className="text-ink-600">
                Can't find what you're looking for?{' '}
                <Link href="mailto:support@copyworx.app" className="text-amber-600 hover:underline">
                  Contact our support team
                </Link>
              </p>
            </div>
            
            {/* FAQ Items */}
            <div className="space-y-4">
              {faqItems.map((item) => (
                <Card key={item.question} className="border-border/50">
                  <CardContent className="p-6">
                    <div className="flex gap-4">
                      <HelpCircle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
                      <div>
                        <h3 className="font-semibold text-ink-900 mb-2">
                          {item.question}
                        </h3>
                        <p className="text-ink-600 text-sm leading-relaxed">
                          {item.answer}
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

