/**
 * @file lib/types/worxdesk.ts
 * @description TypeScript type definitions for the WORX DESK feature.
 *
 * WORX DESK is the AI-assisted brief-to-copy on-ramp. Users paste or upload
 * a creative brief, receive a Strategic Review from an AI copywriter, answer
 * 0-4 clarifying questions, and generate copy that lands directly in the
 * editor. These types cover the full session lifecycle — from raw input through
 * LLM I/O to the metadata persisted on the resulting document.
 */

// ============================================================================
// Session primitives
// ============================================================================

/**
 * A single clarifying question surfaced by the Strategic Review (Call 1).
 * The AI generates 0-4 questions when it determines the brief needs
 * clarification before copy can be generated reliably.
 */
export interface WorxDeskQuestion {
  /** Stable identifier for this question, used to pair it with its answer. */
  id: string;

  /** The human-readable question text shown to the user. */
  text: string;
}

/**
 * The user's response to a single WorxDeskQuestion.
 * Skipped questions are still recorded so the generation prompt can
 * acknowledge gaps rather than silently fabricating answers.
 */
export interface WorxDeskAnswer {
  /** Matches the `id` of the corresponding WorxDeskQuestion. */
  questionId: string;

  /**
   * The text the user typed. Set to an empty string when wasSkipped is true.
   * May also be "don't know" if the user explicitly chose that option.
   */
  answer: string;

  /** True when the user skipped this question rather than answering it. */
  wasSkipped: boolean;
}

// ============================================================================
// Strategic Review (Call 1)
// ============================================================================

/**
 * The parsed output of the Strategic Review LLM call (Call 1).
 * Represents the AI's assessment of the submitted brief and the clarifying
 * questions it needs answered before copy generation can proceed.
 */
export interface WorxDeskStrategicReview {
  /**
   * A short paragraph containing the AI's strategic observation about the
   * brief — tone, positioning, potential risks, or strategic guidance.
   */
  strategicTake: string;

  /**
   * 0-4 clarifying questions generated by the AI. An empty array means the
   * AI determined the brief is sufficient (see briefIsSolid).
   */
  questions: WorxDeskQuestion[];

  /**
   * True when the AI determines the brief is complete enough to proceed
   * directly to generation with no clarifying questions needed.
   */
  briefIsSolid: boolean;

  /**
   * True when the AI determines the brief is fundamentally unworkable
   * (e.g. contradictory goals, missing essential context). When true,
   * the user is prompted to revise before proceeding.
   */
  briefIsBroken: boolean;
}

// ============================================================================
// Session state
// ============================================================================

/**
 * The full in-memory state of a WORX DESK session from brief submission
 * through clarifying Q&A, just before copy generation is triggered.
 * This is ephemeral client-side state; it is not persisted directly.
 * The relevant fields are distilled into WorxDeskMetadata on document save.
 */
export interface WorxDeskSessionState {
  /** The raw brief text the user pasted or typed. */
  originalBrief: string;

  /** Free-text description of the desired output (deliverable type, length, channel). */
  deliverableSpec: string;

  /** Concatenated free text and/or URLs the user supplied as supporting materials. */
  supportingMaterials: string;

  /** The AI@Worx template id the user selected for generation. */
  chosenTemplateId: string;

  /** Brand voice to apply during generation. Null if none selected. */
  brandVoiceId: string | null;

  /** Target persona to apply during generation. Null if none selected. */
  personaId: string | null;

  /** The Strategic Review output from Call 1. Null before the review runs. */
  strategicReview: WorxDeskStrategicReview | null;

  /** The user's answers to the Strategic Review questions (may be empty). */
  answers: WorxDeskAnswer[];

  /**
   * True if the user typed "skip" to bypass the Strategic Review entirely.
   * When true, strategicReview will be null.
   */
  bypassedReview: boolean;

  /**
   * Reserved for future use. Currently always null. Intended to capture
   * a machine-readable reason when bypassedReview is true.
   */
  bypassReason: string | null;
}

// ============================================================================
// Persisted metadata (stored in documents.worxdesk_metadata jsonb column)
// ============================================================================

/**
 * The shape written to the `worxdesk_metadata` jsonb column on the documents
 * table after a WORX DESK session completes and the generated document is
 * saved. Provides full provenance for support, analytics, and future replay.
 */
export interface WorxDeskMetadata {
  /** The raw brief text the user submitted. */
  originalBrief: string;

  /** Free-text description of the deliverable. */
  deliverableSpec: string;

  /** Supporting materials supplied by the user. */
  supportingMaterials: string;

  /** The AI@Worx template id used for generation. */
  chosenTemplateId: string;

  /** Brand voice applied during generation. Null if none was selected. */
  brandVoiceId: string | null;

  /** Target persona applied during generation. Null if none was selected. */
  personaId: string | null;

  /** The Strategic Review AI observation paragraph. */
  strategicTake: string;

  /**
   * Flattened record of every question/answer pair from the session,
   * including skipped questions.
   */
  questionsAndAnswers: Array<{
    question: string;
    answer: string;
    wasSkipped: boolean;
  }>;

  /**
   * The structured form data extracted by the Brief Extraction call (Call 2).
   * Keys are template field identifiers; values are the extracted strings.
   */
  extractedFormData: Record<string, string>;

  /**
   * UUID generated client-side at the start of the WORX DESK session.
   * Ties this document back to the originating session for debugging and
   * analytics.
   */
  worxdeskRunId: string;

  /** True if the user bypassed the Strategic Review. */
  bypassedReview: boolean;

  /** ISO 8601 timestamp of when the WORX DESK session was initiated. */
  createdAt: string;
}

// ============================================================================
// LLM I/O shapes — Call 1: Strategic Review
// ============================================================================

/**
 * Input payload sent to the Strategic Review API route (Call 1).
 * Contains everything the AI needs to assess the brief and generate questions.
 */
export interface StrategicReviewLLMRequest {
  /** The raw creative brief. */
  brief: string;

  /** Description of the desired deliverable. */
  deliverableSpec: string;

  /** Supporting materials provided by the user. */
  supportingMaterials: string;

  /** The target template id, used to tailor the review to the deliverable type. */
  chosenTemplateId: string;

  /** Brand voice id for context. Null if none selected. */
  brandVoiceId: string | null;

  /** Persona id for context. Null if none selected. */
  personaId: string | null;
}

/**
 * Parsed JSON output from the Strategic Review LLM call (Call 1).
 * Structurally identical to WorxDeskStrategicReview — typed separately
 * to make the API boundary explicit and allow divergence in the future.
 */
export type StrategicReviewLLMResponse = WorxDeskStrategicReview;

// ============================================================================
// LLM I/O shapes — Call 2: Brief Extraction
// ============================================================================

/**
 * Input payload sent to the Brief Extraction API route (Call 2).
 * Contains the brief, supporting context, the Strategic Review output, and
 * any clarifying answers the user provided.
 */
export interface BriefExtractionLLMRequest {
  /** The raw creative brief. */
  brief: string;

  /** Description of the desired deliverable. */
  deliverableSpec: string;

  /** Supporting materials provided by the user. */
  supportingMaterials: string;

  /** The AI's strategic observation from Call 1. */
  strategicTake: string;

  /** Answers to the clarifying questions (may be empty if review was bypassed). */
  answers: WorxDeskAnswer[];

  /** The target template id, used to determine which form fields to extract. */
  targetTemplateId: string;
}

/**
 * Parsed JSON output from the Brief Extraction LLM call (Call 2).
 * The formData map is keyed by template field identifiers and contains
 * the extracted values ready to be injected into the generation prompt.
 */
export interface BriefExtractionLLMResponse {
  /**
   * Extracted form data keyed by template field id.
   * All values are strings; empty string means the field could not be
   * extracted from the available context.
   */
  formData: Record<string, string>;
}
